# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c71f536205a5c8f2eb5261bf26b524d81c4c4540bfd4cd35a89fa26ceaba1288cd09bf7e8ba5fea4445ec0b0dd6014b80328230a5d99764f02410929967b78

test:
  secret_key_base: b5df076ff7b03c8807c831eb7d98d1e969baf60ee07fd623e6608f4f28126d07d93432ccf7ebf1ca5f2f7571ac4c2756c49d372d41320a45171eeced8be9e17f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
